export BROWSER=google-chrome-stable
export EDITOR=subl
export TERM_EMU=terminator
export SHELL=/usr/bin/zsh
export FILES=pcmanfm
export PLAYER=vlc
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/bin"
export VISUAL="vim"
# export MANPATH="/usr/local/man:$MANPATH"
