#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $ac_adapt;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $color;
my $icon;
my $status_empty = "";
my $status_quarter = "";
my $status_half = "";
my $status_threequarter = "";
my $status_full = "";
my $status_chr = "";


# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
	$status = 'DIS';
} elsif ($status eq 'Charging') {
	$status = 'CHR';
} elsif ($status eq 'Full') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);

	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;

		if ($ac_adapt eq 'on-line') {
			$status = 'CHR';
		} elsif ($ac_adapt eq 'off-line') {
			$status = 'DIS';
		}
	}
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# consider color and urgent flag only on discharge
if ($status eq 'DIS') {
	if ($percent < 25) {
		$color = "#FF0000";
      $icon = $status_empty;
	} elsif ($percent < 50) {
		$color = "#FFAE00";
      $icon = $status_quarter;
	} elsif ($percent < 75) {
		$color = "#FFF600";
      $icon = $status_half;
	} elsif ($percent < 95) {
		$color = "#A8FF00";
      $icon = $status_threequarter;
	} else {
		$color = "#FFFFFF";
      $icon = $status_full;
   }
} elsif ($status eq 'CHR') {
   $color = "#FFFFFF";
   $icon = $status_chr;
} else {
}

# print text
print "<span foreground='$color'>$icon</span><span font='8' rise='14000'>$full_text</span>\n";
print "<span foreground='$color'>$icon</span><span font='8' rise='14000'>$short_text</span>\n";

if ($percent < 5) {
   exit(33);
}

exit(0);
