#!/bin/bash
# Copyright (C) 2018 Faham Negini <faham.negini@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#----------------------------------------------

full_text=''
short_text=''
color='#FFFFFF'
urgent=false
icon=''
t_warn=50;
t_crit=80;
cpu_usage=0

#----------------------------------------------

cpu_usage=$(mpstat 1 1 | grep -A 5 "%idle" | tail -n 1 | awk -F " " '{print 100 -  $ 12}'a) # 100% - %idle

if [ "$cpu_usage" -ge "$t_crit" ]; then
   color='#FF0000'
   urget=true
elif [ "$cpu_usage" -ge "$t_warn" ]; then
   color='#FFFC00'
fi

case $BLOCK_BUTTON in
    1) i3-msg -q -- exec xterm -title "htop" -e htop &> /dev/null ;;  # left click
    *) ;;
esac

full_text=$(printf "%s" \
   "<span foreground='${color}'>${icon}</span>" \
   "<span font='8' rise='14000' foreground='${color}'>${cpu_usage}%</span>" \
)
short_text=$full_text

#----------------------------------------------

echo $full_text
echo $short_text
echo $color

if [ "$urgent" = true ]; then
   exit 33
else
   exit 0
fi

