#!/bin/bash


URL="https://google.com"

while getopts u:h opt; do
    case "$opt" in
        u) URL="$OPTARG" ;;
        h) printf \
"Usage: volume-pulseaudio [-u Url] [-h]
Options:
-u\tUrl to access. Default '$URL'
" && exit 0;;
    esac
done

exec google-chrome-stable --app=$URL &> /dev/null &


