#!/bin/sh

case $1 in
up)
    xbacklight -inc 1;;
down)
    xbacklight -dec 1;;
*)
    exit 1;;
esac


percent=$(xbacklight -get | cut -d. -f1)

osd_pid='/tmp/osd.pid'
osd_cmd="osd_cat \
   --shadow=1 --shadowcolour=#333333 --color=#FFFFFF \
  --pos=bottom --offset=30 --align=center \
  --lines=2 --delay=1 --barmode=percentage --percentage=$percent"

if [[ -f $osd_pid ]]; then
    kill $(cat $osd_pid) 2> /dev/null;
fi

($osd_cmd --font="-*-dejavu sans-bold-r-*-*-32-*-*-*-*-*-*-*" --text="Brightness: $percent") &
echo $! > $osd_pid
