#!/bin/sh

DISPLAY_0=eDP1
DISPLAY_1=DP1

if [[ 'connected' == `xrandr --query | grep "^$DISPLAY_1" | cut -d' ' -f2` ]]; then
    xrandr --auto --output $DISPLAY_1 --right-of $DISPLAY_0 --primary
    echo "extended to two screens"
    [ `cat /etc/hostname` = "x1-faham" ] && \
      xrandr --output $DISPLAY_1 --mode 3840x2160 --primary --output $DISPLAY_0 --auto  --left-of $DISPLAY_1;
else
    xrandr --auto --output $DISPLAY_0 --primary
fi

xset r rate 175 50

