#!/bin/sh

DISPLAY_0=eDP1      #Primary Display
DISPLAY_1=HDMI1

if [[ 'connected' == `xrandr --query | grep "^$DISPLAY_1" | cut -d' ' -f2` ]]; then
    echo "Two screens, Extended ($DISPLAY_0 right of $DISPLAY_1 primary)"
    [ `cat /etc/hostname` = "faham-x1" ] && \
        # xrandr --auto --output $DISPLAY_1 --right-of $DISPLAY_0 --primary;
        # xrandr --output $DISPLAY_1 --mode 3840x2160 \
        #        --output $DISPLAY_0 --primary --auto --left-of $DISPLAY_1;

        # xrandr --output $DISPLAY_0 --auto --right-of $DISPLAY_1;
        # xrandr --output $DISPLAY_1 --scale 2x2 --mode 1920x1080 --fb 6400x2160 --pos 0x0 \
        #        --output $DISPLAY_0 --scale 1x1 --pos 3840x0;

        xrandr --auto --output $DISPLAY_1 --above $DISPLAY_0 --primary;
        xrandr --fb $((2*1920))x$(((2*1080)+1440)) \
               --output $DISPLAY_1 --scale 2x2 --mode 1920x1080 --pos 0x0 \
               --output $DISPLAY_0 --scale 1x1 --pos 0x$((2*1080));
else
    echo "One screen ($DISPLAY_0 primary)"
    xrandr --auto --output $DISPLAY_0 --primary
fi

# signalling screen i3block
pkill -RTMIN+8 i3blocks

xset r rate 170 50

