#!/bin/bash

set -e
set -o pipefail

USER=faham
FILES=$HOME/.scripts/files

pacman -S sudo patch --noconfirm

usermod -G disk --append $USER
usermod -G sys --append $USER

[ -f /etc/gdm/custom.conf ] && sed  -i "s/^#WaylandEnable=false/WaylandEnable=false/" /etc/gdm/custom.conf
patch -r - /etc/sudoers $FILES/sudoers.patch
patch -r - /etc/pacman.conf $FILES/pacman.conf.patch
cp $FILES/motd /etc/motd
cp $FILES/screenlock-suspend.service /usr/lib/systemd/system/
cp $FILES/screenlock-hibernate.service /usr/lib/systemd/system/

PACKAGES="
base-dev aria2 cmake cmus ctags cups downgrade evince exfat-utils
fluxbox freerdp gdb ghostscript gimp git gparted gsfonts gvfs
gvfs-mtp htop i3-wm i3lock i3blocks imagemagick libva-intel-driver
libvdpau-va-gl linux-headers mesa-libgl nmap ntfs-3g openssh p7zip
pcmanfm pulseaudio python-pip python2 python2-pip qalculate-gtk
rdesktop rsync samba scrot sshfs terminus-font tk tmux ttf-bitstream-vera
ttf-dejavu ttf-font-awesome ttf-freefont ttf-inconsolata ttf-liberation
ttf-linux-libertine ttf-ubuntu-font-family unclutter unzip vim vim-spell-en vlc
wget wpa_actiond xautolock xbindkeys xclip xdot xdotool xf86-input-synaptics
xf86-video-intel xloadimage xorg-apps xorg-fonts-100dpi xorg-fonts-75dpi
xorg-server xorg-xinit xorg-xmessage xosd xterm yaourt youtube-dl zip zsh
mplayer mosh rofi sysstat acpi w3m alsa-utils ruby ripgrep rxvt-unicode
highlight mediainfo tig neofetch eog perl nnn bat exa fd tldr ranger
"
#pm-utils xorg-server-utils

pacman -Syy
pacman -S $PACKAGES --noconfirm

systemctl enable screenlock-suspend.service
systemctl start screenlock-suspend.service
systemctl enable screenlock-hibernate.service
systemctl start screenlock-hibernate.service
systemctl enable sshd.service
systemctl start sshd.service
systemctl enable sshd.socket
systemctl start sshd.socket
systemctl enable netctl-auto@.service
systemctl start netctl-auto@.service
systemctl enable org.cups.cupsd.service
systemctl start org.cups.cupsd.service

$HOME/.scripts/set-python 2
pip install twisted argparse
$HOME/.scripts/set-python 3

ln -s /etc/fonts/conf.avail/ /etc/fonts/conf.d

# required groups membership for cups administration at http://http://127.0.0.1:631/
gpasswd -a $USER lp
gpasswd -a $USER sys

su $USER
YAOURT_PKGS="
google-chrome git-crypt xvkbd laptop-mode-tools tpacpi-bat rxvt-unicode-pixbuf
polybar persian-fonts
"
yaourt -S "${YAOURT_PKGS}"
git submodule update --init --recursive

# install zplug
(cd $HOME; curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh)

su root
[ -f /usr/bin/subl ] || ln -s /usr/bin/subl3 /usr/bin/subl
[ -f /etc/ssh/sshd_config ] && patch -r - /etc/ssh/sshd_config $FILES/sshd_config.patch

