#!/bin/bash

set -e
set -o pipefail

yum install -y sudo git zsh htop wget curl epel-release mosh yum-utils

firewall-cmd --zone=public --add-port=60000-61000/udp --permanent
firewall-cmd --reload

rpm -Uvh https://centos7.iuscommunity.org/ius-release.rpm
yum install -y gcc-c++ ncurses-devel python-devel tmux2u python36u \
               python36u-libs python36u-devel python36u-pip ruby ruby-devel \
               lua-devel luajit-devel perl-devel perl-ExtUtils-Embed

ln -nfs /usr/bin/python3.6 /usr/bin/python3

yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
yum install ripgrep

mkdir ~/src
git clone https://github.com/vim/vim.git ~/src/vim
cd ~/src/vim/src
./configure \
    --enable-multibyte \
    --enable-perlinterp=dynamic \
    --enable-rubyinterp=dynamic \
    --with-ruby-command=/usr/bin/ruby \
    --enable-pythoninterp=dynamic \
    --with-python-config-dir=/usr/lib64/python2.7/config \
    --enable-luainterp \
    --with-luajit \
    --enable-cscope \
    --with-features=huge \
    --enable-fontset \
    --enable-largefile \
    --disable-netbeans \
    --with-compiledby="Faham Negini <faham@ethicadata.com>" \
    --disable-nls \
    --enable-gui=no \
    --with-tlib=ncurses \
    --without-x \
    --enable-fail-if-missing \
    --prefix=/usr/local/vim
    # --enable-python3interp \
    # --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu \
make -j4
make install
ln -nfs /usr/local/vim/bin/vim /usr/bin/vim


# intall Nginx
cp ./files/nginx.repo /etc/yum.repos.d/nginx.repo
yum install nginx

# install pip and virtualenv
yum makecache
yum install python-pip
pip install virtualenv

# requirements for python-ldap
yum install openldap-devel

