#!/bin/bash

set -e
set -o pipefail

USER=faham
HOME=/home/$USER

pacman -S sudo patch --noconfirm

usermod -G disk --append $USER
usermod -G sys --append $USER

[ -f /etc/gdm/custom.conf ] && sed  -i "s/^#WaylandEnable=false/WaylandEnable=false/" /etc/gdm/custom.conf
patch -r - /etc/sudoers $HOME/bin/files/sudoers.patch
patch -r - /etc/pacman.conf $HOME/bin/files/pacman.conf.patch
cp $HOME/bin/files/motd /etc/motd

PACKAGES="
bashrun            p7zip                   vlc
cmake              pcmanfm                 wget
conky              xclip
ctags              pulseaudio              xdot
cups               python-pip              xdotool
downgrade          python2                 xf86-input-synaptics
evince             python2-pip             xf86-video-intel
exfat-utils        qalculate-gtk           xloadimage
festival-us        rdesktop                xorg-apps
fluxbox            samba                   xorg-server
freerdp            scrot                   wpa_actiond
ghostscript        sshfs                   xorg-xinit
gimp               cmus                    xorg-xmessage
git                tk                      xosd
tmux               xscreensaver
gparted            ttf-bitstream-vera      xterm
gpicview           ttf-dejavu              yaourt
gsfonts            ttf-freefont            youtube-dl
gvfs               ttf-inconsolata         zip
htop               ttf-liberation          zsh
imagemagick        ttf-linux-libertine     rsync
libimobiledevice   ttf-ubuntu-font-family  gvfs-mtp
libva-intel-driver unclutter               xbindkeys
libvdpau-va-gl     unzip                   mutagen
linux-headers      vim                     fakeroot
mesa-libgl         vim-spell-en            picard
nmap               virtualbox              autoconf
ntfs-3g            virtualbox-guest-utils  gdb
openssh            virtualbox-host-dkms    patch
sudo               automake                pkg-config
aria2              terminus-font           xorg-fonts-100dpi
xorg-fonts-75dpi
"

#pm-utils xorg-server-utils

pacman -Syy
pacman -S $PACKAGES --noconfirm

systemctl enable sshd.service
systemctl start sshd.service
systemctl enable sshd.socket
systemctl start sshd.socket
systemctl enable netctl-auto@.service
systemctl start netctl-auto@.service

$HOME/bin/set-python 2
pip install twisted argparse
$HOME/bin/set-python 3

ln -s /etc/fonts/conf.avail/ /etc/fonts/conf.d

# required groups membership for cups administration at http://http://127.0.0.1:631/
gpasswd -a $USER lp
gpasswd -a $USER sys

su $USER
yaourt -S google-chrome sublime-text-dev \
   git-crypt xvkbd laptop-mode-tools
git submodule update --init --recursive

su root
[ -f /usr/bin/subl ] || ln -s /usr/bin/subl3 /usr/bin/subl
[ -f /etc/ssh/sshd_config ] && patch -r - /etc/ssh/sshd_config $HOME/bin/files/sshd_config.patch

