#!/bin/bash

pntDevId=$( xinput list | grep "pointer" | grep -v "Virtual" | grep -o "id=[0-9]*" | cut -d= -f2 )

# disable all pointing devices
for f in $pntDevId
do
   xinput set-prop $f "Device Enabled" "0"
done

# this must be the last command, and it must be 'non forking', as expected by 'xautolock'
# i3lock -c 272822 -n -e -f -t -i /tmp/temp.png
# i3lock-wrapper -l -n -e
xset dpms force off
i3lock -n -e -c 272822

# enable all pointing devices
for f in $pntDevId
do
   xinput set-prop $f "Device Enabled" "1"
done
