#!/bin/bash

# if "off" is given as parameter, then spawn a new thread to turn off the screen
[ "$1" = "off" ] && $(sleep 1 &&  xset dpms force off) &

# this must be the last command, and it must be 'non forking', as expected by 'xautolock'
# i3lock -c 272822 -n -e -f -t -i /tmp/temp.png
i3lock-wrapper -l -n -e
