#!/bin/bash

osd_pid='/tmp/osd.pid'

if [[ -f $osd_pid ]]; then
    kill $(cat $osd_pid) 2> /dev/null;
    rm $osd_pid
fi

if [[ -n "$1" ]]; then
   echo "$1" | osd_cat \
      --shadow=1 --shadowcolour=#333333 --color=#FFFFFF --pos=bottom --offset=100 \
      --align=center --indent=0 --lines=1 --delay=2 \
      --font="-*-dejavu sans-bold-r-*-*-64-*-*-*-*-*-*-*" &

   echo $! >> $osd_pid
else
   DATE=$( date +"%a %h %d, %I:%M:%S" )

   echo $DATE | osd_cat \
      --shadow=1 --shadowcolour=#333333 --color=#FFFFFF --pos=bottom --offset=100 \
      --align=center --indent=0 --lines=1 --delay=2 \
      --font="-*-dejavu sans-bold-r-*-*-64-*-*-*-*-*-*-*" &

   echo $! >> $osd_pid
fi

