#!/bin/bash

BAT="Battery: $( cat /sys/class/power_supply/BAT0/capacity )% $( cat /sys/class/power_supply/BAT0/status )"
DATE=$( date )
BKLIGHT="Brightness: $( xbacklight -get | cut -d. -f1 )%"

osd_pid='/tmp/osd.pid'

if [[ -f $osd_pid ]]; then
    kill $(cat $osd_pid) 2> /dev/null;
    rm $osd_pid
fi

echo "$BKLIGHT $BAT" | osd_cat \
   --shadow=1 --shadowcolour=#333333 --color=#FFFFFF --pos=bottom --offset=60 \
   --align=center --indent=0 --lines=1 --delay=2 \
   --font="-*-dejavu sans-bold-r-*-*-32-*-*-*-*-*-*-*" &

echo $! >> $osd_pid

echo $DATE | osd_cat \
   --shadow=1 --shadowcolour=#333333 --color=#FFFFFF --pos=bottom --offset=100 \
   --align=center --indent=0 --lines=1 --delay=2 \
   --font="-*-dejavu sans-bold-r-*-*-64-*-*-*-*-*-*-*" &

echo $! >> $osd_pid
