#!/bin/sh
#
# pdfsplit [input.pdf] [first_page] [last_page] [output.pdf] 
#
# Example: pdfsplit big_file.pdf 10 20 pages_ten_to_twenty.pdf

if [ $# -lt 4 ]; then
   echo "Usage: pdfsplit input.pdf first_page last_page output.pdf"
   exit 1
fi

gs -dNOPAUSE -dBATCH -q -sOutputFile="$4" -dFirstPage=$2 -dLastPage=$3 -sDEVICE=pdfwrite "$1" >& /dev/null

