#!/bin/sh

VER=$1

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

rm -f /usr/bin/python /usr/bin/python-config
[ -f "/usr/bin/python$VER" ] && ln -s "/usr/bin/python$VER" /usr/bin/python
[ -f "/usr/bin/python$VER-config" ] && ln -s "/usr/bin/python$VER-config" /usr/bin/python-config
