#!/bin/bash

case $1 in
up)
    mixer_option='+1%';;
down)
    mixer_option='-1%';;
toggle)
    mixer_option='toggle';;
*)
    exit 1;;
esac

if [[ $mixer_option == 'toggle' ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ $mixer_option
else
    pactl set-sink-volume @DEFAULT_SINK@ $mixer_option
fi

volume_percent=$(echo "scale=2; $(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | tr -d '%')" | bc)
volume_mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep '^\s*Mute:' | head -1 | cut -d' ' -f 2)

if [[ $volume_mute == 'yes' ]]; then
    volume_mute='[Mute]'
else
    volume_mute=''
fi

osd_pid='/tmp/osd.pid'
osd_cmd="osd_cat \
  --shadow=1 --shadowcolour=#333333 --color=#FFFFFF \
  --pos=bottom --offset=30 --align=center \
  --lines=2 --delay=1 --barmode=percentage --percentage=$volume_percent"

if [[ -f $osd_pid ]]; then
    kill $(cat $osd_pid) 2> /dev/null;
fi

# signalling brightness i3block
pkill -RTMIN+9 i3blocks

($osd_cmd --font="-*-dejavu sans-bold-r-*-*-32-*-*-*-*-*-*-*" --text="Master Volume: $volume_percent $volume_mute") &
echo $! > $osd_pid
