#!/bin/bash

case $1 in
up)
    mixer_option='+1%';;
down)
    mixer_option='-1%';;
toggle)
    mixer_option='toggle';;
*)
    exit 1;;
esac

if [[ $mixer_option == 'toggle' ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ $mixer_option
else
    pactl set-sink-volume @DEFAULT_SINK@ $mixer_option
fi

DEFAULT_SINK=$(pacmd dump | grep "default-sink" | cut -d' ' -f2)

volume_percent=$(pactl list sinks | sed -n -E -e "/$DEFAULT_SINK/,$ p" | grep '^\s*Volume:' | head -1 | grep -Eo '^[^%]+' | rev | cut -d' ' -f 1 | rev)
volume_mute=$(pactl list sinks | sed -n -E -e "/$DEFAULT_SINK/,$ p" | grep '^\s*Mute:' | head -1 | cut -d' ' -f 2)

if [[ $volume_mute == 'yes' ]]; then
    volume_mute='[Mute]'
else
    volume_mute=''
fi

osd_pid='/tmp/osd-volume.pid'
osd_cmd="osd_cat \
  --shadow=1 --shadowcolour=#333333 --color=#FFFFFF \
  --pos=bottom --offset=30 --align=center \
  --lines=2 --delay=1 --barmode=percentage --percentage=$volume_percent"

if [[ -f $osd_pid ]]; then
    kill $(cat $osd_pid) 2> /dev/null;
fi

($osd_cmd --font="-*-dejavu sans-bold-r-*-*-32-*-*-*-*-*-*-*" --text="Master Volume: $volume_percent $volume_mute") &
echo $! > $osd_pid
